site_name: Отчёты по лабораторным работам

nav:
  - Главная: index.md
  - Лабораторная работа №1:
    - Задача 1: task1.md
    - Задача 2: task2.md
    - Задача 3: task3.md
    - Задача 4: task4.md
    - Задача 5: task5.md

  - Лабораторная работа №2:
    - Табло победителей автогонок: lab2.md

  - Лабораторная работа №3:
    - Сервис лизинга авто: lab3.md

  - Практическая работа №3:
      - 3.1: pr31.md
      - 3.2: pr32.md

theme:
  name: material
  language: ru